#!/usr/bin/bash

_thync() {
	_thync_vars() {
		_thync_vars_define() {
			local flags
			flags=('-t' '--type')
			
			COMPREPLY=($(compgen -W "$( __thync_get_variable_names )" -- "${COMP_WORDS[${COMP_CWORD}]}"));
		}

		_thync_vars_get() {
			return
		}

		_thync_vars_set() {
			# TODO: Get variable names
			return
		}

		local command
		command="${COMP_CWORDS[2]}"

		if [[ "$COMP_CWORD" -eq 2 ]]; then
			local commands
			commands=('define' 'get' 'set')
			
			COMPREPLY=($(compgen -W "${commands[*]}" -- "$command"))
		else
			__thync_test_function "_thync_vars_$command"
		fi
	}

	_thync_profiles() {
		case "$2" in
			'new') ;;
			'delete') ;;
			'set') ;;
			*) ;;
		esac
	}

	_thync_bind() {
		case "$2" in
			*) ;;
		esac
	}

	_thync_plugins() {
		case "$2" in
			*) ;;
		esac	
	}

	__thync_get_variable_names() {
		cut -f 1 "${XDG_CONFIG_HOME:$HOME/.config/thync/variables}"
	}

	__thync_test_function() {
		type -t "$1" > /dev/null && eval "$1"
	}

	local command
	command="${COMP_WORDS[1]}"

	# Complete the top-level noun if requrested
	if [[ "$COMP_CWORD" -eq 1 ]]; then
		local commands
		commands=('vars' 'profile' 'plugins' 'targets' 'bind')
		
		COMPREPLY=($(compgen -W "${commands[*]}" -- "$command"))
	else
		__thync_test_function "_thync_$command"
	fi
} && complete -F _thync thync

